// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Breadcrumb: typeof import("./../components/Breadcrumb/index.vue")["default"];
    ElAffix: typeof import("element-plus/es")["ElAffix"];
    ElAlert: typeof import("element-plus/es")["ElAlert"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCascader: typeof import("element-plus/es")["ElCascader"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElInputNumber: typeof import("element-plus/es")["ElInputNumber"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElText: typeof import("element-plus/es")["ElText"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ElTree: typeof import("element-plus/es")["ElTree"];
    ElTreeSelect: typeof import("element-plus/es")["ElTreeSelect"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    GithubCorner: typeof import("./../components/GithubCorner/index.vue")["default"];
    Hamburger: typeof import("./../components/Hamburger/index.vue")["default"];
    IconSelect: typeof import("./../components/IconSelect/index.vue")["default"];
    IEpArrowDown: typeof import("~icons/ep/arrow-down")["default"];
    IEpArrowLeft: typeof import("~icons/ep/arrow-left")["default"];
    IEpCalendar: typeof import("~icons/ep/calendar")["default"];
    IEpCaretBottom: typeof import("~icons/ep/caret-bottom")["default"];
    IEpCaretTop: typeof import("~icons/ep/caret-top")["default"];
    IEpChatDotRound: typeof import("~icons/ep/chat-dot-round")["default"];
    IEpCircleCloseFilled: typeof import("~icons/ep/circle-close-filled")["default"];
    IEpClose: typeof import("~icons/ep/close")["default"];
    IEpCollection: typeof import("~icons/ep/collection")["default"];
    IEpDArrowRight: typeof import("~icons/ep/d-arrow-right")["default"];
    IEpDelete: typeof import("~icons/ep/delete")["default"];
    IEpDownload: typeof import("~icons/ep/download")["default"];
    IEpEdit: typeof import("~icons/ep/edit")["default"];
    IEpPlus: typeof import("~icons/ep/plus")["default"];
    IEpRefresh: typeof import("~icons/ep/refresh")["default"];
    IEpRefreshLeft: typeof import("~icons/ep/refresh-left")["default"];
    IEpRefreshRight: typeof import("~icons/ep/refresh-right")["default"];
    IEpSearch: typeof import("~icons/ep/search")["default"];
    IEpSetting: typeof import("~icons/ep/setting")["default"];
    IEpTop: typeof import("~icons/ep/top")["default"];
    IEpUploadFilled: typeof import("~icons/ep/upload-filled")["default"];
    LangSelect: typeof import("./../components/LangSelect/index.vue")["default"];
    MultiUpload: typeof import("./../components/Upload/MultiUpload.vue")["default"];
    Pagination: typeof import("./../components/Pagination/index.vue")["default"];
    PicturePreview: typeof import("./../components/Upload/PicturePreview.vue")["default"];
    RightPanel: typeof import("./../components/RightPanel/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Screenfull: typeof import("./../components/Screenfull/index.vue")["default"];
    SingleUpload: typeof import("./../components/Upload/SingleUpload.vue")["default"];
    SizeSelect: typeof import("./../components/SizeSelect/index.vue")["default"];
    SvgIcon: typeof import("./../components/SvgIcon/index.vue")["default"];
    TaxSourceSelect: typeof import("./../components/taxSourceSelect/index.vue")["default"];
    WangEditor: typeof import("./../components/WangEditor/index.vue")["default"];
    ZxnBottomBtn: typeof import("./../components/zxnBottomBtn/index.vue")["default"];
    ZxnButtonGroup: typeof import("./../components/zxnButtonGroup/index.vue")["default"];
    ZxnDateRange: typeof import("./../components/zxnDateRange/index.vue")["default"];
    ZxnPlan: typeof import("./../components/zxnPlan/index.vue")["default"];
    ZxnSearch: typeof import("./../components/zxnSearch/index.vue")["default"];
    ZxnTable: typeof import("./../components/zxnTable/index.vue")["default"];
    ZxnTabs: typeof import("./../components/zxnTabs/index.vue")["default"];
    ZxnTitle: typeof import("./../components/zxnTitle/index.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
